export const currencies = [
  { code: "USD", name: "Dólar estadounidense" },
  { code: "EUR", name: "Euro" },
  { code: "ARS", name: "Peso argentino" },
  { code: "BOB", name: "Boliviano" },
  { code: "BRL", name: "Real brasileño" },
  { code: "CLP", name: "Peso chileno" },
  { code: "COP", name: "Peso colombiano" },
  { code: "CRC", name: "Colón costarricense" },
  { code: "CUP", name: "Peso cubano" },
  { code: "DOP", name: "Peso dominicano" },
  { code: "ECU", name: "Dólar ecuatoriano" },
  { code: "GTQ", name: "Quetzal guatemalteco" },
  { code: "HNL", name: "Lempira hondureño" },
  { code: "MXN", name: "Peso mexicano" },
  { code: "NIO", name: "Córdoba nicaragüense" },
  { code: "PAB", name: "Balboa panameño" },
  { code: "PEN", name: "Sol peruano" },
  { code: "PYG", name: "Guaraní paraguayo" },
  { code: "SVC", name: "Colón salvadoreño" },
  { code: "UYU", name: "Peso uruguayo" },
  { code: "VES", name: "Bolívar soberano venezolano" },
]

